### ISSUE TITLE
TypeError: Cannot read property 'LayoutParams' of undefined

### ISSUE THREAD

**Issue by agrawal-mohit** [NativeScript/nativescript-sdk-examples-ng#95]
Geny emulator Android API21
tns 2.3.0

Im trying to build a camera component in my app.

**html**

```
<StackLayout exampleTitle toggleNavButtonrm>
    <ScrollView>
        <!-- >> camera-module-html -->
        <FlexboxLayout flexDirection="column-reverse">
            <Image [src]="imageTaken" flexGrow="3" class="img-rounded"></Image>  
            <Button text="Take Photo" class="btn btn-primary btn-active" (tap)="onTakePhoto()" flexGrow="1"></Button>
            <Button text="Request permissions" class="btn btn-primary btn-active" (tap)="onRequestPermissions()" flexGrow="1"></Button>         
        </FlexboxLayout>
        <!-- << camera-module-html -->
    </ScrollView>
</StackLayout>
```

**component.ts**
```

import { Component } from "@angular/core";
import { ImageAsset } from "image-asset";
import * as camera from "nativescript-camera";

@Component({
    selector: 'using-camera-component',
    templateUrl: 'pages/createexpense/expense-photo.html'
})

export class ExpensePhotoComponent {
   
    public imageTaken: ImageAsset;
    public saveToGallery: boolean = true;
    public keepAspectRatio: boolean = true;
    public width: number = 300;
    public height: number = 300;

    onTakePhoto() {
        var options = { width: this.width, height: this.height, keepAspectRatio: this.keepAspectRatio,  saveToGallery: this.saveToGallery };
        camera.takePicture(options)
            .then(imageAsset => {
                this.imageTaken = imageAsset;
                console.log("Size: " + imageAsset.options.width + "x" + imageAsset.options.height);
            }).catch(err => {
                console.log(err.message);
            })
    }
    
    onRequestPermissions() {
        camera.requestPermissions();
    }
   

    onCheckForCamera() {
        var isCameraAvailable = camera.isAvailable();
        console.log("Is camera hardware available: " + isCameraAvailable);
    }

}
```

This is the log  : 
<img width="407" alt="screen shot 2016-11-01 at 21 12 50" src="https://cloud.githubusercontent.com/assets/1859165/19895772/083af698-a078-11e6-84a4-0b3f9d371538.png">

**Comment by NickIliev** [comment]
Hey @agrawal-mohit 

Try updating your tons-core-modules and tns-core-modules-widgets

```
tns plugin add tns-core-modules@next
tns plugin add ins-core-modules-widgets@next
```

**Comment by agrawal-mohit** [comment]
@NickIliev Tried that, didn't solve it.

**Comment by NickIliev** [comment]
Have your removed your platforms and node_modules folder before rebuilding your application
```
rm -rf node_mopdules
rm -rf platforms
tns plugin add tns-core-modules@next
tns plugin add tns-core-modules-widgets@next
```

The error you are logging is caused by the lack of the new functionalities like FlexboxLayout and ImageAsset which are coming with nativeScript 2.4.0 so updating the modules and rebuilding your app should fix it. If not can you  please provide the error log (preferably no as screenshot but as text file or git gist )

**Comment by agrawal-mohit** [comment]
This is what I'm getting now : 
```

node_modules/nativescript-angular/http/ns-http.d.ts(8,22): error TS2415: Class 'NSHttp' incorrectly extends base class 'Http'.
  Types of property 'get' are incompatible.
    Type '(url: string, options?: RequestOptionsArgs) => Observable<Response>' is not assignable to type '(url: string, options?: RequestOptionsArgs) => Observable<Response>'.
      Type 'Observable<Response>' is not assignable to type 'Observable<Response>'.
        Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.

```

**Comment by NickIliev** [comment]
The last issue you are hitting is related to [this one](https://github.com/NativeScript/nativescript-angular/issues/393) and also some users have hit it and discussed it [here](https://github.com/NativeScript/nativescript-angular/issues/397#issuecomment-240496553)

Try the solution suggested in the last issue as follows:

> In your package.json file, please use this for now:
> 
> "nativescript-angular": "next"
> Until a new version is released.

**Comment by agrawal-mohit** [comment]
I've made the changes suggested in these posts. This is what shows in my terminal : 
```

app/app.module.ts(7,10): error TS2305: Module '"/Users/mohit/work/Mobile/native/finly-ng/node_modules/nativescript-angular/http"' has no exported member 'NS_HTTP_PROVIDERS'.

node_modules/nativescript-angular/http/ns-http.d.ts(8,22): error TS2415: Class 'NSHttp' incorrectly extends base class 'Http'.
  Types of property 'get' are incompatible.
    Type '(url: string, options?: RequestOptionsArgs) => Observable<Response>' is not assignable to type '(url: string, options?: RequestOptionsArgs) => Observable<Response>'.
      Type 'Observable<Response>' is not assignable to type 'Observable<Response>'.
        Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.


```

These are my files : 
[NS Files.zip](https://github.com/NativeScript/nativescript-sdk-examples-ng/files/571107/NS.Files.zip)

**Comment by agrawal-mohit** [comment]
@NickIliev I have create a dummy project that reproduces the problem. Could you please check and verify if it works for you ? I have updated the tns-core-modules to 2.5 but strangely i am still getting the error. Here's the repo - https://github.com/agrawal-mohit/fundoo/tree/master

**Comment by NickIliev** [comment]
@agrawal-mohit the link above is dead .
However, I think you issue might be related to [this one](Class 'NSHttp' incorrectly extends base class 'Http') so perhaps you can try the suggested workarounds.
I am closing this issue as it is not related to the application here but more likely is related to a configuration problem.
